### ISSUE TITLE
Json books

### ISSUE THREAD

**Issue by vox-nox** [shrieking-antshrikes/berrynet#4]
There are some books that return an html page. 
select another?
![html](https://cloud.githubusercontent.com/assets/11148581/6883657/76b0ad56-d57d-11e4-858c-0c053c4b3ca7.png)

**Comment by jleeothon** [comment]
I'll double-check them again. That's weird. Are you sure it's only some of them? Do you have an example?

**Comment by vox-nox** [comment]
This is due to error 403
#5
